export const materialdata = [
  "Normal",
  "Star",
  "Vinyl",
  "Vinyl + Lamination",
  "Backlight",
  "Reflect Flex",
  "Reflect Vinyl",
  "Eco Vinyl",
  "Eco Vinyl + Lamination",
  "UV Star",
  "UV Vinyl",
  "UV Backlight",
  "Sunpack Sheet",
  "Foarm Board 3mm",
  "Foarm Board 4mm",
  "Foarm Board 5mm",
  "Frame + Noraml",
  "Frame + Star",
  "Frame + Backlight",
];
